# Generated by Django 4.2.7 on 2023-12-03 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extended',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
